
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from saat import *
from tkinter import messagebox

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from pymsgbox import password

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\17769\Desktop\Python\UserLogin\giris\giris_assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

user= "mert"
passw= "12345"

def control():
    user_name = user_name_v.get()
    user_password = user_password_v.get()
    if user_name == user and user_password == passw:
        print("Giriş Başarılı.")
        window.destroy()
        clock_f()
    else:
        messagebox.showwarning("Uyarı","Kullanıcı Adı Veya Şifre Hatalı.")
        print("Kullanıcı Adı Veya Şifre Hatalı.")



window = Tk()
window.title("Giriş Sayfası")
window.geometry("600x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 600,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    300.0,
    200.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    300.0,
    108.0,
    image=entry_image_1
)
user_name_v = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
user_name_v.place(
    x=201.0,
    y=95.0,
    width=198.0,
    height=24.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    300.0,
    150.0,
    image=entry_image_2
)
user_password_v = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show = "*"
)
user_password_v.place(
    x=201.0,
    y=137.0,
    width=198.0,
    height=24.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command= control,
    relief="flat"
)
button_1.place(
    x=314.0,
    y=178.0,
    width=85.0,
    height=27.0
)
window.resizable(False, False)
window.mainloop()
