from gettext import textdomain
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from datetime import datetime

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from scipy.constants import minute

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\17769\Desktop\Python\UserLogin\giris\saat_assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def clock_f():
    def dongu():
        now= datetime.now()
        hour= now.hour
        minute = now.minute
        saat_d = str(hour)+":"+str(minute)
        saat_d = "{:02d}:{:02d}".format(hour, minute)
        canvas.itemconfig(saat,text=saat_d)
        window.after(1000,dongu)


    window = Tk()
    window.title("Saat")
    window.geometry("600x576")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 576,
        width = 600,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("saat_bg.png"))
    image_1 = canvas.create_image(
        300.0,
        288.0,
        image=image_image_1
    )

    saat = canvas.create_text(
        299.99999999999994,
        95.0,
        anchor="nw",
        text="00.00",
        fill="#000000",
        font=("ComicNeue Bold", 64 * -1)
    )

    dongu()

    window.resizable(False, False)
    window.mainloop()
